server:
  port: 8080

spring:
  application:
    name: play-vault-backend
    api-prefix: /api
  datasource:
    url: jdbc:mysql://localhost:3307/playvaultdb?createDatabaseIfNotExist=true
    username: root
    password: 20112004
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB
  ai:
    ollama:
      base-url: http://localhost:11434  # URL mặc định của Ollama
      embedding:
        model: bge-m3:latest       # Tên model bạn đã pull về
      chat:
        enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 30000 # 5min
    refreshTokenExpiration: 604800 # 7 days
  mail:
    host: smtp.gmail.com
    port: 587
    username: phucvinh20112004@gmail.com
    password: xmnh pvos vncb lpmo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: phucvinh20112004@gmail.com
    default-encoding: UTF-8
    test-connection: true

gdrive:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/api/drive/oauth2callback
    tokens-file: ./gdrive-oauth-tokens.json
  parent-folder-id: "1R1qSJPn2ktOyJQXz0BfEErPx7TdZYZrA"

payment:
  vnPay:
#    url: ${PAY_URL}
#    tmnCode: ${TMN_CODE}
#    secretKey: ${SECRET_KEY}
#    returnUrl: ${RETURN_URL}
#    version: ${VERSION}
#    command: ${COMMAND}
#    orderType: ${ORDER_TYPE}

    # Các giá trị này khớp với @Value("${payment.vnPay...}") trong VNPAYConfig.java
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    returnUrl: http://localhost:8080/api/v1/payment/vn-pay-callback
    tmnCode: 58X4B4HP
    secretKey: VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ
    version: 2.1.0
    command: pay
    orderType: other