server:
  port: 8080

spring:
  application:
    name: play-vault-backend

  datasource:
    url: jdbc:mysql://localhost:3306/playvaultdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100GB
      max-request-size: 100GB

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 30000
    refreshTokenExpiration: 604800

  mail:
    host: smtp.gmail.com
    port: 587
    username: phucvinh20112004@gmail.com
    password: xmnh pvos vncb lpmo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: phucvinh20112004@gmail.com
    default-encoding: UTF-8
    test-connection: true

  ai:
    vectorstore:
      qdrant:
        initialize-schema: true
        collection-name: playvault_collection
        vector-dimension: 768
        host: localhost
        port: 6334
        use-tls: false

    ollama:
      base-url: http://localhost:11434

      # CHỈ DÙNG EMBEDDING – KHÔNG CẦN CHAT
      embedding:
        options:
          model: nomic-embed-text:latest   # SIÊU NHẸ + SIÊU CHUẨN
      chat:
        options:
          model: qwen2.5:3b   # Hoặc "llama3.2:3b" hoặc "qwen2.5:1.5b"
          temperature: 0.3     # Để thấp (0.3 - 0.5) giúp model tập trung dùng tool chính xác hơn
          keep_alive: "60m"
          num-ctx: 2048

gdrive:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/api/drive/oauth2callback
    tokens-file: ./gdrive-oauth-tokens.json
  parent-folder-id: "1R1qSJPn2ktOyJQXz0BfEErPx7TdZYZrA"

logging:
  level:
    # Bật DEBUG log để hiển thị chi tiết JSON Payload và HTTP Request gửi tới Ollama
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG