server:
  port: 8080

spring:
  application:
    name: play-vault-backend
  datasource:
    url: jdbc:mysql://localhost:3306/playvaultdb?createDatabaseIfNotExist=true
    username: root
    password: 22718451
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5min
    refreshTokenExpiration: 604800 # 7 days
  mail:
    host: smtp.gmail.com
    port: 587
    username: phucvinh20112004@gmail.com
    password: xmnh pvos vncb lpmo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: phucvinh20112004@gmail.com
    default-encoding: UTF-8
    test-connection: true